// src/constants/notificationTypes.js
const NotificationTypes = {
    ORDER: {
      CREATED: 'ORDER_CREATED',
      CONFIRMED: 'ORDER_CONFIRMED',
      PREPARED: 'ORDER_PREPARED',
      READY: 'ORDER_READY',
      CANCELLED: 'ORDER_CANCELLED'
    },
    PAYMENT: {
      INITIATED: 'PAYMENT_INITIATED',
      COMPLETED: 'PAYMENT_COMPLETED',
      FAILED: 'PAYMENT_FAILED',
      REFUNDED: 'PAYMENT_REFUNDED'
    },
    DELIVERY: {
      ASSIGNED: 'DELIVERY_ASSIGNED',
      PICKED_UP: 'DELIVERY_PICKED_UP',
      COMPLETED: 'DELIVERY_COMPLETED',
      DELAYED: 'DELIVERY_DELAYED'
    },
    RESTAURANT: {
      ACCEPTED_ORDER: 'RESTAURANT_ACCEPTED_ORDER',
      REJECTED_ORDER: 'RESTAURANT_REJECTED_ORDER'
    },
    USER: {
      WELCOME: 'USER_WELCOME',
      PASSWORD_RESET: 'USER_PASSWORD_RESET',
      ACCOUNT_UPDATED: 'USER_ACCOUNT_UPDATED'
    }
  };
  
  module.exports = NotificationTypes;
  
