-- Create ENUM types directly in each table definition (MySQL doesn't support separate ENUM types)

-- Table: Carts
CREATE TABLE Carts (
  CartID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  RestaurantID INT NOT NULL,
  Status ENUM('ACTIVE', 'COMPLETED') DEFAULT 'ACTIVE',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: CartItems
CREATE TABLE CartItems (
  CartItemsID INT AUTO_INCREMENT PRIMARY KEY,
  CartID INT NOT NULL,
  MenuItemID INT NOT NULL,
  Quantity INT DEFAULT 1,
  Price FLOAT NOT NULL,
  CONSTRAINT FK_CartItems_CartID FOREIGN KEY (CartID) REFERENCES Carts(CartID)
);

-- Table: Orders
CREATE TABLE Orders (
  OrderID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  RestaurantID INT NOT NULL,
  CartID INT NOT NULL,
  TotalAmount FLOAT NOT NULL,
  Status ENUM('Pending', 'Completetd', 'Failed') DEFAULT 'Pending',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table: OrderItems
CREATE TABLE OrderItems (
  OrderItemsID INT AUTO_INCREMENT PRIMARY KEY,
  OrderID INT NOT NULL,
  MenuItemID INT NOT NULL,
  Quantity INT NOT NULL,
  Price FLOAT NOT NULL,
  CONSTRAINT FK_OrderItems_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);
